# PySNMP SMI module. Autogenerated from smidump -f python CLOUDANT-REG-MIB
# by libsmi2pysnmp-0.1.3 at Mon Feb 18 12:34:34 2013,
# Python version sys.version_info(major=2, minor=7, micro=2, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( Bits, Integer32, ModuleIdentity, MibIdentifier, ObjectIdentity, TimeTicks, enterprises, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "ObjectIdentity", "TimeTicks", "enterprises")

# Objects

cloudant = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277))
if mibBuilder.loadTexts: cloudant.setDescription("The IANA has assigned enterprise branch 40277 to Cloudant.")
cloudantReg = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 1))
if mibBuilder.loadTexts: cloudantReg.setDescription("Sub-tree for identification of Modules and logical components.")
cloudantModules = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 1, 1))
if mibBuilder.loadTexts: cloudantModules.setDescription("Sub-tree to register the values assigned to modules with the \nMODULE-IDENTITY construct. Core MIBs are registered under this branch.")
cloudantRegMibModule = ModuleIdentity((1, 3, 6, 1, 4, 1, 40277, 1, 1, 1)).setRevisions(("2012-07-29 23:00",))
if mibBuilder.loadTexts: cloudantRegMibModule.setOrganization("Cloudant, Inc.")
if mibBuilder.loadTexts: cloudantRegMibModule.setContactInfo("580 Harrison Ave., Boston, MA 02118, USA")
if mibBuilder.loadTexts: cloudantRegMibModule.setDescription("Cloudant Global Registration MIB")
cloudantPlatformModule = MibIdentifier((1, 3, 6, 1, 4, 1, 40277, 1, 1, 2))
cloudantDbcoreModule = MibIdentifier((1, 3, 6, 1, 4, 1, 40277, 1, 1, 3))
cloudantLoadBalancerModule = MibIdentifier((1, 3, 6, 1, 4, 1, 40277, 1, 1, 4))
cloudantClouseauModule = MibIdentifier((1, 3, 6, 1, 4, 1, 40277, 1, 1, 5))
cloudantMetricsModule = MibIdentifier((1, 3, 6, 1, 4, 1, 40277, 1, 1, 6))
cloudantPlugins = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 1, 2))
if mibBuilder.loadTexts: cloudantPlugins.setDescription("Sub-tree to register plugin modules. Plugins with their own specific MIBs\nare registered under this branch.")
cloudantGeneric = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 2))
if mibBuilder.loadTexts: cloudantGeneric.setDescription("Sub-tree for objects and events common to Cloudant products and subsystems.")
cloudantPlatformMIB = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 2, 1))
if mibBuilder.loadTexts: cloudantPlatformMIB.setDescription("Sub-tree for all generic objects and events related to the Cloudant\nplatform.")
cloudantProducts = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 3))
if mibBuilder.loadTexts: cloudantProducts.setDescription("Sub-tree for objects and events for specific Cloudant products and modules.")
cloudantDbcoreMIB = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 3, 1))
if mibBuilder.loadTexts: cloudantDbcoreMIB.setDescription("The MIB for the Cloudant DB Core. All objects and events are defined\nunder this branch.")
cloudantLoadBalancerMIB = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 3, 2))
if mibBuilder.loadTexts: cloudantLoadBalancerMIB.setDescription("The MIB for the Cloudant Load Balancer. All objects and events are\ndefined under this branch.")
cloudantClouseauMIB = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 3, 3))
if mibBuilder.loadTexts: cloudantClouseauMIB.setDescription("The MIB for Cloudant Clouseau Search. All objects and events are\ndefined under this branch.")
cloudantMetricsMIB = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 3, 4))
if mibBuilder.loadTexts: cloudantMetricsMIB.setDescription("The MIB for Cloudant Metrics. All objects and events are\ndefined under this branch.")
cloudantCaps = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 4))
if mibBuilder.loadTexts: cloudantCaps.setDescription("Sub-tree for agent implementation profiles.")
cloudantReqs = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 5))
if mibBuilder.loadTexts: cloudantReqs.setDescription("Sub-tree for Management Application module requirements.")
cloudantExpr = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 6))
if mibBuilder.loadTexts: cloudantExpr.setDescription("Sub-tree for experimental definitions and new development.")

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("CLOUDANT-REG-MIB", PYSNMP_MODULE_ID=cloudantRegMibModule)

# Objects
mibBuilder.exportSymbols("CLOUDANT-REG-MIB", cloudant=cloudant, cloudantReg=cloudantReg, cloudantModules=cloudantModules, cloudantRegMibModule=cloudantRegMibModule, cloudantPlatformModule=cloudantPlatformModule, cloudantDbcoreModule=cloudantDbcoreModule, cloudantLoadBalancerModule=cloudantLoadBalancerModule, cloudantClouseauModule=cloudantClouseauModule, cloudantMetricsModule=cloudantMetricsModule, cloudantPlugins=cloudantPlugins, cloudantGeneric=cloudantGeneric, cloudantPlatformMIB=cloudantPlatformMIB, cloudantProducts=cloudantProducts, cloudantDbcoreMIB=cloudantDbcoreMIB, cloudantLoadBalancerMIB=cloudantLoadBalancerMIB, cloudantClouseauMIB=cloudantClouseauMIB, cloudantMetricsMIB=cloudantMetricsMIB, cloudantCaps=cloudantCaps, cloudantReqs=cloudantReqs, cloudantExpr=cloudantExpr)

