# PySNMP SMI module. Autogenerated from smidump -f python CLOUDANT-CLOUSEAU-MIB
# by libsmi2pysnmp-0.1.3 at Mon May  6 15:26:05 2013,
# Python version sys.version_info(major=2, minor=7, micro=2, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( cloudantTrapLevel, ) = mibBuilder.importSymbols("CLOUDANT-PLATFORM-MIB", "cloudantTrapLevel")
( cloudantClouseauMIB, cloudantModules, ) = mibBuilder.importSymbols("CLOUDANT-REG-MIB", "cloudantClouseauMIB", "cloudantModules")
( Bits, Integer32, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks")

# Objects

cloudantClouseauModule = ModuleIdentity((1, 3, 6, 1, 4, 1, 40277, 1, 1, 5)).setRevisions(("2012-07-30 04:00",))
if mibBuilder.loadTexts: cloudantClouseauModule.setOrganization("Cloudant, Inc.")
if mibBuilder.loadTexts: cloudantClouseauModule.setContactInfo("580 Harrison Ave., Boston, MA 02118, USA")
if mibBuilder.loadTexts: cloudantClouseauModule.setDescription("Cloudant Clouseau Search object and event definition MIB")
cloudantClouseauObjects = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 3, 3, 1))
if mibBuilder.loadTexts: cloudantClouseauObjects.setDescription("Sub-tree for accessible objects in the MIB.")
cloudantClouseauEvents = ObjectIdentity((1, 3, 6, 1, 4, 1, 40277, 3, 3, 2))
if mibBuilder.loadTexts: cloudantClouseauEvents.setDescription("A sub-tree for all the CLOUDANT-CLOUSEAU-MIB related events\nand traps.")

# Augmentions

# Notifications

cloudantClouseauRebootEvent = NotificationType((1, 3, 6, 1, 4, 1, 40277, 3, 3, 2, 1)).setObjects(*(("CLOUDANT-PLATFORM-MIB", "cloudantTrapLevel"), ) )
if mibBuilder.loadTexts: cloudantClouseauRebootEvent.setDescription("This event is generated when the Clouseau Search service\nis restarted on the given node.")

# Exports

# Module identity
mibBuilder.exportSymbols("CLOUDANT-CLOUSEAU-MIB", PYSNMP_MODULE_ID=cloudantClouseauModule)

# Objects
mibBuilder.exportSymbols("CLOUDANT-CLOUSEAU-MIB", cloudantClouseauModule=cloudantClouseauModule, cloudantClouseauObjects=cloudantClouseauObjects, cloudantClouseauEvents=cloudantClouseauEvents)

# Notifications
mibBuilder.exportSymbols("CLOUDANT-CLOUSEAU-MIB", cloudantClouseauRebootEvent=cloudantClouseauRebootEvent)

